language: cpp


compiler:
  - g++
  
script:
  - ./bsys/buildMe.sh 


after_script:
  #- ./test/reg/runRegTests.sh
  # - kpsewhich tkz-graph.sty


after_success:
  - echo " shat lava "
  #- chmod 777 ./test/reg/runRegTests.sh
  #- ./test/reg/runRegTests.sh
 
after_failure:
  - echo "build failure"
  
