language: cpp


compiler:
  - g++
  
script:
  - make
  - chmod 777 ./test/reg/runRegTests.sh
  - chmod 777 ./test/unit/runUnitTests.sh
  - chmod 777 ./test/unit/tests/*
  - ./bsys/utils/runTests.sh

after_script:
  #- ./test/reg/runRegTests.sh
  # - kpsewhich tkz-graph.sty


after_success:
  - echo " shat lava "
  #- chmod 777 ./test/reg/runRegTests.sh
  #- ./test/reg/runRegTests.sh
 
after_failure:
  - echo "build failure"
  
